name: ApprovalPlugin
version: 1.0
main: com.davis.approvalplugin.Main
api-version: '1.21'
commands:
  approve:
    description: Approva un giocatore bloccato
    usage: /approve <player>
    permission: approvalplugin.approve

permissions:
  approvalplugin.approve:
    description: Permette di approvare giocatori
    default: op
